name: Deploy to Staging

on:
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm i
      - name: Pull YAML data
        run: ./tools/sync_data.sh
      - name: Build the project
        run: npm run build
      - name: Deploy to Netlify
        uses: jsmrcaga/action-netlify-deploy@master
        with:
          install_command: echo "Dependencies are already installed"
          build_command: echo "Project is already built"
          build_directory: public
          NETLIFY_DEPLOY_TO_PROD: true
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Deploy staging from commit ${{ github.sha }}"
      - name: Commit built artifacts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: release
          file_pattern: public/**/*
          commit_message: 'Update built artifacts'
